theme: jekyll-theme-minimal
title: Nikoleta Papadopoulou
description: Bookmark this to keep an eye on my project updates!

github_username: nikolpapad

nav:
  - Home: /
  - Projects: /projects/
  - About: /about/
  - CV: /cv/
