theme: jekyll-theme-minimal
title: Nikoleta Papadopoulou
description: Bookmark this to keep an eye on my project updates!

## ðŸ‘‹ About Me
Follow me as I navigate through learning about GenAI, Robotics and everything in between. 
## ðŸš€ My Projects
- **Project 1** â€“ Crochet patterns
- **Project 2** â€“ Custom website theme.
- **Project 3** â€“ Experimenting with CycleGANs ;) 

## ðŸ“¬ Contact
Feel free to reach out at: nikolpanpap@gmail.com

# Add navigation
nav:
  - Home: /
  - Projects: /projects/
  - About: /about/

